[package]
name = "aleo-rust"
version = "0.3.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Tools for getting data from the Aleo API & forming transactions"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "operating-systems" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.anyhow]
version = "1.0.68"

[dependencies.reqwest]
version = "0.11.14"
optional = true
default-features = false

[dependencies.ureq]
version = "2.6.2"

[dependencies.indexmap]
version = "1.9.2"

[dependencies.once_cell]
version = "1.13.1"

[dependencies.rand]
version = "0.8"

[dependencies.snarkvm]
workspace = true
features = [ "parallel" ]

[dependencies.serde_json]
version = "1.0.91"

[dev-dependencies.rand]
version = "0.8.0"

[dev-dependencies.rand_chacha]
version = "0.3.0"
default-features = false

[dev-dependencies.bencher]
version = "0.1.5"

[features]
default = [ ]
async = [ "reqwest" ]
